interface SlackNotificationPayload {
  title: string;
  startTime: string;
  endTime: string;
  participants: Array<{
    name: string;
    email: string;
  }>;
  summary: string;
  meetingId: string;
}

interface BookingSlackNotificationPayload {
  booking: {
    id: number;
    hash: string;
    host_user_id: string;
    person_user_id: string;
    first_name: string;
    last_name: string;
    email: string;
    message: string;
    start_time: string;
    end_time: string;
    location_details: {
      online_platform_link?: string;
    };
  };
  calendar_event?: any;
}

interface SlackMessage {
  text: string;
  blocks?: Array<{
    type: string;
    text?: {
      type: string;
      text: string;
    };
    fields?: Array<{
      type: string;
      text: string;
    }>;
    accessory?: any;
  }>;
}

export async function sendSlackNotification(payload: SlackNotificationPayload): Promise<void> {
  const slackWebhookUrl = process.env.SLACK_WEBHOOK_URL;
  
  if (!slackWebhookUrl) {
    throw new Error('SLACK_WEBHOOK_URL environment variable is not configured');
  }

  // Format the start and end times
  const startTime = new Date(payload.startTime).toLocaleString();
  const endTime = new Date(payload.endTime).toLocaleString();
  
  // Create participant list
  const participantList = payload.participants
    .map(p => `• ${p.name} (${p.email})`)
    .join('\n');

  // Create the Slack message with rich formatting
  const slackMessage: SlackMessage = {
    text: `New Meeting Report: ${payload.title}`,
    blocks: [
      {
        type: "header",
        text: {
          type: "plain_text",
          text: `📅 Meeting Report: ${payload.title}`
        }
      },
      {
        type: "section",
        fields: [
          {
            type: "mrkdwn",
            text: `*Meeting ID:*\n${payload.meetingId}`
          },
          {
            type: "mrkdwn",
            text: `*Duration:*\n${startTime} - ${endTime}`
          }
        ]
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*Participants:*\n${participantList}`
        }
      },
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*Summary:*\n${payload.summary}`
        }
      },
      {
        type: "divider"
      },
      {
        type: "context",
        elements: [
          {
            type: "mrkdwn",
            text: `Generated by DailySync Webhook System at ${new Date().toLocaleString()}`
          }
        ]
      }
    ]
  };

  try {
    const response = await fetch(slackWebhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(slackMessage),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Slack API error: ${response.status} ${response.statusText} - ${errorText}`);
    }

    console.log('Slack notification sent successfully');
  } catch (error) {
    console.error('Failed to send Slack notification:', error);
    throw error;
  }
}

// Alternative simple text notification function
export async function sendSimpleSlackNotification(text: string): Promise<void> {
  const slackWebhookUrl = process.env.SLACK_WEBHOOK_URL;
  
  if (!slackWebhookUrl) {
    throw new Error('SLACK_WEBHOOK_URL environment variable is not configured');
  }

  const slackMessage = {
    text: text
  };

  try {
    const response = await fetch(slackWebhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(slackMessage),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Slack API error: ${response.status} ${response.statusText} - ${errorText}`);
    }

    console.log('Simple Slack notification sent successfully');
  } catch (error) {
    console.error('Failed to send simple Slack notification:', error);
    throw error;
  }
}

// Enhanced booking notification function with template support
export async function sendBookingSlackNotification(payload: BookingSlackNotificationPayload, processedTemplate?: string): Promise<void> {
  const slackWebhookUrl = process.env.SLACK_WEBHOOK_URL;

  if (!slackWebhookUrl) {
    throw new Error('SLACK_WEBHOOK_URL environment variable is not configured');
  }

  const { booking } = payload;

  // Use processed template if provided, otherwise create a default message
  let processedMessage: string;

  if (processedTemplate) {
    // Use the template that was already processed by TemplateProcessor
    processedMessage = processedTemplate;
  } else {
    // Fallback to simple default message if no template was processed
    const startTime = new Date(booking.start_time).toLocaleString();
    const endTime = new Date(booking.end_time).toLocaleString();
    const fullName = `${booking.first_name} ${booking.last_name}`.trim();
    const onlinePlatformLink = booking.location_details?.online_platform_link || 'Not provided';

    processedMessage = `📅 *New Booking Received*

👤 *Customer:* ${fullName}
📧 *Email:* ${booking.email}
🕐 *Start Time:* ${startTime}
🕑 *End Time:* ${endTime}
🔗 *Meeting Link:* ${onlinePlatformLink}
👥 *Host ID:* ${booking.host_user_id}
👤 *Person ID:* ${booking.person_user_id}

💬 *Message:*
${booking.message || 'No message provided'}

---
🤖 *Booking Details:*
• ID: ${booking.id}
• Hash: ${booking.hash}`;
  }

  const slackMessage = {
    text: '📅 New Booking Received',
    blocks: [
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: processedMessage
        }
      },
      {
        type: 'divider'
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: `🤖 Sent via DeskSync Webhook System | Booking ID: ${booking.id}`
          }
        ]
      }
    ]
  };

  try {
    const response = await fetch(slackWebhookUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(slackMessage),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Slack API error: ${response.status} ${response.statusText} - ${errorText}`);
    }

    console.log('Booking Slack notification sent successfully');
  } catch (error) {
    console.error('Failed to send booking Slack notification:', error);
    throw error;
  }
}

// Test function to verify Slack integration
export async function testSlackIntegration(): Promise<boolean> {
  try {
    await sendSimpleSlackNotification('🧪 Test message from DailySync webhook system - Slack integration is working!');
    return true;
  } catch (error) {
    console.error('Slack integration test failed:', error);
    return false;
  }
}
